### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by Nuflanmohamed** [nextvikas/yii2-nextchat#1]
*** applying m211121_105223_user_table
    > execute SQL: ALTER TABLE `user` ADD `online` INT NOT NULL DEFAULT '0'; ...Exception 'yii\db\Exception' with message 'SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'online'
The SQL being executed was: ALTER TABLE `user` ADD `online` INT NOT NULL DEFAULT '0';'

in /home/nuflan/Nuflan/test-projects/new /basic/vendor/yiisoft/yii2/db/Schema.php:674

Error Info:
Array
(
    [0] => 42S21
    [1] => 1060
    [2] => Duplicate column name 'online'
)

**Comment by nextvikas** [comment]
@Nuflanmohamed 
Please remove and reinstall
it should work now
