### ISSUE TITLE
console error im using basic yii

### ISSUE THREAD

**Issue by Nuflanmohamed** [nextvikas/yii2-nextchat#2]
PHP Fatal Error – yii\base\ErrorException
Class 'common\models\User' not found
1. in /home/nuflan/Nuflan/test-projects/new /basic/vendor/nextvikas/yii2-nextchat/models/User.phpat line 7
12345678910111213141516<?php
namespace nextvikas\nextchat\models;
use Yii;
use common\models\User as chatingUser;
use nextvikas\nextchat\models\FriendsList;
 
class User extends chatingUser
{
 
    public function getfrndrequest($id) {
        $res = FriendsList::find()->select('friend_one')->where(['friend_two'=>$id,'status'=>0])->asArray()->all();
        return $res;
    }
 
    public function get($id){
        return self::find()
2. yii\base\ErrorHandler::handleFatalError()

**Comment by nextvikas** [comment]
@Nuflanmohamed 
Please use Yii2 advanced instead of basic
